### PR TITLE
Don't add script when in admin mode

### PR DESCRIPTION
**Pull request by Bellfalasch**

### CODE REVIEW

**Comment by Michael-Lazell** [comment]
There is no "sitename". There is only "shortname". When you set up your Disqus account for a site, it's called "shortname" and that is what goes in the code. Looks like you just changed this to "sitename". We should keep it as "shortname" to match the Disqus documentation.  See here https://help.disqus.com/customer/portal/articles/472097-universal-embed-code and here https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables

**Comment by Bellfalasch** [comment]
Oh, it looked so different from shortname (old format was ID-like, "d8f76sdrgf" and new format was word-like, "examplesite"). So that's why I assumed it was something new for their embed code.

Should we keep the name as shortname then and remove sitename altogether?

This pull request fixes another issue that needs fixing (the "don't add comment count script when inside admin as it collides with some XP scripts"). I can commit fixes for the shortname/sitename issue before you approve the pull.

**Comment by Michael-Lazell** [comment]
Sure, go ahead. I think you get to make your shortname when you set up the
Disqus account for your site. I've done it a few times, but it was a while
ago so can't remember for sure. I thought maybe the changed things and got
rid of the shortname, but when I looked at their documentation yesterday,
it still says shortname everywhere.



Best regards
Enonic AS

Michael Lazell
Services Manager Americas

Mobile +1 (415) 774-6090
Norwegian office +47 22 00 85 50

https://enonic.com - A web operating system for your sites and applications

**Comment by Bellfalasch** [comment]
This is now tested and works. Only shortname for site is there. I think what happened to me was that I missed to create a shortname and just got a random one. And then later when generating my embed code I got to set the shortname, thus thinking they were to different things.

Anyways, all is fixed in the code now. Extra setting is dropped.

**Pull request merged**
